import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/common/SideBar";
import { UidProvider } from "@/contexts/id";
import { EmailAndNameProvider } from "@/contexts/emailAndName";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Club Space",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UidProvider>
          <EmailAndNameProvider>
            <main>
              <SideBar />
              {children}
            </main>
          </EmailAndNameProvider>
        </UidProvider>
      </body>
    </html>
  );
}
