import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Navbar from "@/components/common/navbar";
// import { useRouter} from 'next/router';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //  const router = useRouter();
  //  const excludeRoutes = ['/signin', '/signup', '/forgotpassword'];

   //const shouldDisplayNavbar = !excludeRoutes.includes(router.pathname);

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* {shouldDisplayNavbar && <Navbar />} */}
        <main>{children}</main>
      </body>
    </html>
  );
}
